// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbGs039ar7UKaUHVgtf-1rB0CbaxxkzK4',
    appId: '1:728178703066:web:88268f6cb253d2815cc3e3',
    messagingSenderId: '728178703066',
    projectId: 'e-foodie-8b2f8',
    authDomain: 'e-foodie-8b2f8.firebaseapp.com',
    storageBucket: 'e-foodie-8b2f8.firebasestorage.app',
    measurementId: 'G-PK3DV2YXT0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPRWAPrEQm0xgL8IZ8r8SFj7kWUPnp4Pk',
    appId: '1:728178703066:android:9e6fae4df5b4fe2c5cc3e3',
    messagingSenderId: '728178703066',
    projectId: 'e-foodie-8b2f8',
    storageBucket: 'e-foodie-8b2f8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyButznSAaIDdkLR9j3kPZJAZVwyiOmeym8',
    appId: '1:728178703066:ios:a767b8e66c320f035cc3e3',
    messagingSenderId: '728178703066',
    projectId: 'e-foodie-8b2f8',
    storageBucket: 'e-foodie-8b2f8.firebasestorage.app',
    iosBundleId: 'A.Ahad.eFoodie',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyButznSAaIDdkLR9j3kPZJAZVwyiOmeym8',
    appId: '1:728178703066:ios:a767b8e66c320f035cc3e3',
    messagingSenderId: '728178703066',
    projectId: 'e-foodie-8b2f8',
    storageBucket: 'e-foodie-8b2f8.firebasestorage.app',
    iosBundleId: 'A.Ahad.eFoodie',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbGs039ar7UKaUHVgtf-1rB0CbaxxkzK4',
    appId: '1:728178703066:web:1f893c48e2d4b5845cc3e3',
    messagingSenderId: '728178703066',
    projectId: 'e-foodie-8b2f8',
    authDomain: 'e-foodie-8b2f8.firebaseapp.com',
    storageBucket: 'e-foodie-8b2f8.firebasestorage.app',
    measurementId: 'G-P6JXR0TZHV',
  );
}
